
version: "3"

services:

  boot-app:
  image: book-app-crud-demo
  ports:
   - "8080" : 8080
  depends_on:
   - mysql-db

  mysql-db:
  image: mysql:8
  environment:
   - MYSQL_ROOT_PASSWORD = root
   - MYSQL_DATABASE = root
