server:
  port: 9090
spring:
  datasource:
    #driverClassName: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/springboot
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
