spring:
  mail:
    host: your-smtp-host
    port: your-smtp-port
    username: santoshlimbale76@gmail.com
    password: Developer&143
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/springboot?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
  file:
    name: book-application.log